import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import "./globals.css";
import Navigation from "@/components/Header/Header";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '500', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Оренда техніки у Києві +380958202612",
  description: "Generated by create next app",
  icons: {
    icon: "/icon-icons.png", // шлях до твого файлу в public/
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
